/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgendarRouteImport } from './routes/agendar'
import { Route as AjudaRouteImport } from './routes/ajuda'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as EmpresasRouteImport } from './routes/empresas'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as HomeRouteImport } from './routes/home'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PagamentosRouteImport } from './routes/pagamentos'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as QrcodeRouteImport } from './routes/qrcode'
import { Route as ReservasRouteImport } from './routes/reservas'
import { Route as ViagensRouteImport } from './routes/viagens'
import { Route as EmpresaIdRouteImport } from './routes/empresa.$id'
import { Route as PainelIndexRouteImport } from './routes/painel.index'
import { Route as PainelAgendamentoRouteImport } from './routes/painel.agendamento'
import { Route as PainelAvaliacoesRouteImport } from './routes/painel.avaliacoes'
import { Route as PainelContatosRouteImport } from './routes/painel.contatos'
import { Route as PainelEmpresaRouteImport } from './routes/painel.empresa'
import { Route as PainelFinanceiroRouteImport } from './routes/painel.financeiro'
import { Route as PainelQrcodeRouteImport } from './routes/painel.qrcode'
import { Route as PainelReservasRouteImport } from './routes/painel.reservas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendarRoute = AgendarRouteImport.update({
  id: '/agendar',
  path: '/agendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AjudaRoute = AjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresasRoute = EmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentosRoute = PagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const QrcodeRoute = QrcodeRouteImport.update({
  id: '/qrcode',
  path: '/qrcode',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservasRoute = ReservasRouteImport.update({
  id: '/reservas',
  path: '/reservas',
  getParentRoute: () => rootRouteImport,
} as any)
const ViagensRoute = ViagensRouteImport.update({
  id: '/viagens',
  path: '/viagens',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresaIdRoute = EmpresaIdRouteImport.update({
  id: '/empresa/$id',
  path: '/empresa/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelIndexRoute = PainelIndexRouteImport.update({
  id: '/painel/',
  path: '/painel/',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelAgendamentoRoute = PainelAgendamentoRouteImport.update({
  id: '/painel/agendamento',
  path: '/painel/agendamento',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelAvaliacoesRoute = PainelAvaliacoesRouteImport.update({
  id: '/painel/avaliacoes',
  path: '/painel/avaliacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelContatosRoute = PainelContatosRouteImport.update({
  id: '/painel/contatos',
  path: '/painel/contatos',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelEmpresaRoute = PainelEmpresaRouteImport.update({
  id: '/painel/empresa',
  path: '/painel/empresa',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelFinanceiroRoute = PainelFinanceiroRouteImport.update({
  id: '/painel/financeiro',
  path: '/painel/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelQrcodeRoute = PainelQrcodeRouteImport.update({
  id: '/painel/qrcode',
  path: '/painel/qrcode',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelReservasRoute = PainelReservasRouteImport.update({
  id: '/painel/reservas',
  path: '/painel/reservas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agendar': typeof AgendarRoute
  '/ajuda': typeof AjudaRoute
  '/cadastro': typeof CadastroRoute
  '/empresas': typeof EmpresasRoute
  '/historico': typeof HistoricoRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/pagamentos': typeof PagamentosRoute
  '/perfil': typeof PerfilRoute
  '/qrcode': typeof QrcodeRoute
  '/reservas': typeof ReservasRoute
  '/viagens': typeof ViagensRoute
  '/empresa/$id': typeof EmpresaIdRoute
  '/painel/agendamento': typeof PainelAgendamentoRoute
  '/painel/avaliacoes': typeof PainelAvaliacoesRoute
  '/painel/contatos': typeof PainelContatosRoute
  '/painel/empresa': typeof PainelEmpresaRoute
  '/painel/financeiro': typeof PainelFinanceiroRoute
  '/painel/qrcode': typeof PainelQrcodeRoute
  '/painel/reservas': typeof PainelReservasRoute
  '/painel/': typeof PainelIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agendar': typeof AgendarRoute
  '/ajuda': typeof AjudaRoute
  '/cadastro': typeof CadastroRoute
  '/empresas': typeof EmpresasRoute
  '/historico': typeof HistoricoRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/pagamentos': typeof PagamentosRoute
  '/perfil': typeof PerfilRoute
  '/qrcode': typeof QrcodeRoute
  '/reservas': typeof ReservasRoute
  '/viagens': typeof ViagensRoute
  '/empresa/$id': typeof EmpresaIdRoute
  '/painel/agendamento': typeof PainelAgendamentoRoute
  '/painel/avaliacoes': typeof PainelAvaliacoesRoute
  '/painel/contatos': typeof PainelContatosRoute
  '/painel/empresa': typeof PainelEmpresaRoute
  '/painel/financeiro': typeof PainelFinanceiroRoute
  '/painel/qrcode': typeof PainelQrcodeRoute
  '/painel/reservas': typeof PainelReservasRoute
  '/painel': typeof PainelIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agendar': typeof AgendarRoute
  '/ajuda': typeof AjudaRoute
  '/cadastro': typeof CadastroRoute
  '/empresas': typeof EmpresasRoute
  '/historico': typeof HistoricoRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/pagamentos': typeof PagamentosRoute
  '/perfil': typeof PerfilRoute
  '/qrcode': typeof QrcodeRoute
  '/reservas': typeof ReservasRoute
  '/viagens': typeof ViagensRoute
  '/empresa/$id': typeof EmpresaIdRoute
  '/painel/agendamento': typeof PainelAgendamentoRoute
  '/painel/avaliacoes': typeof PainelAvaliacoesRoute
  '/painel/contatos': typeof PainelContatosRoute
  '/painel/empresa': typeof PainelEmpresaRoute
  '/painel/financeiro': typeof PainelFinanceiroRoute
  '/painel/qrcode': typeof PainelQrcodeRoute
  '/painel/reservas': typeof PainelReservasRoute
  '/painel/': typeof PainelIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agendar'
    | '/ajuda'
    | '/cadastro'
    | '/empresas'
    | '/historico'
    | '/home'
    | '/login'
    | '/pagamentos'
    | '/perfil'
    | '/qrcode'
    | '/reservas'
    | '/viagens'
    | '/empresa/$id'
    | '/painel/agendamento'
    | '/painel/avaliacoes'
    | '/painel/contatos'
    | '/painel/empresa'
    | '/painel/financeiro'
    | '/painel/qrcode'
    | '/painel/reservas'
    | '/painel/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agendar'
    | '/ajuda'
    | '/cadastro'
    | '/empresas'
    | '/historico'
    | '/home'
    | '/login'
    | '/pagamentos'
    | '/perfil'
    | '/qrcode'
    | '/reservas'
    | '/viagens'
    | '/empresa/$id'
    | '/painel/agendamento'
    | '/painel/avaliacoes'
    | '/painel/contatos'
    | '/painel/empresa'
    | '/painel/financeiro'
    | '/painel/qrcode'
    | '/painel/reservas'
    | '/painel'
  id:
    | '__root__'
    | '/'
    | '/agendar'
    | '/ajuda'
    | '/cadastro'
    | '/empresas'
    | '/historico'
    | '/home'
    | '/login'
    | '/pagamentos'
    | '/perfil'
    | '/qrcode'
    | '/reservas'
    | '/viagens'
    | '/empresa/$id'
    | '/painel/agendamento'
    | '/painel/avaliacoes'
    | '/painel/contatos'
    | '/painel/empresa'
    | '/painel/financeiro'
    | '/painel/qrcode'
    | '/painel/reservas'
    | '/painel/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendarRoute: typeof AgendarRoute
  AjudaRoute: typeof AjudaRoute
  CadastroRoute: typeof CadastroRoute
  EmpresasRoute: typeof EmpresasRoute
  HistoricoRoute: typeof HistoricoRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  PagamentosRoute: typeof PagamentosRoute
  PerfilRoute: typeof PerfilRoute
  QrcodeRoute: typeof QrcodeRoute
  ReservasRoute: typeof ReservasRoute
  ViagensRoute: typeof ViagensRoute
  EmpresaIdRoute: typeof EmpresaIdRoute
  PainelAgendamentoRoute: typeof PainelAgendamentoRoute
  PainelAvaliacoesRoute: typeof PainelAvaliacoesRoute
  PainelContatosRoute: typeof PainelContatosRoute
  PainelEmpresaRoute: typeof PainelEmpresaRoute
  PainelFinanceiroRoute: typeof PainelFinanceiroRoute
  PainelQrcodeRoute: typeof PainelQrcodeRoute
  PainelReservasRoute: typeof PainelReservasRoute
  PainelIndexRoute: typeof PainelIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendar': {
      id: '/agendar'
      path: '/agendar'
      fullPath: '/agendar'
      preLoaderRoute: typeof AgendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajuda': {
      id: '/ajuda'
      path: '/ajuda'
      fullPath: '/ajuda'
      preLoaderRoute: typeof AjudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresas': {
      id: '/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof EmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamentos': {
      id: '/pagamentos'
      path: '/pagamentos'
      fullPath: '/pagamentos'
      preLoaderRoute: typeof PagamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qrcode': {
      id: '/qrcode'
      path: '/qrcode'
      fullPath: '/qrcode'
      preLoaderRoute: typeof QrcodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservas': {
      id: '/reservas'
      path: '/reservas'
      fullPath: '/reservas'
      preLoaderRoute: typeof ReservasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viagens': {
      id: '/viagens'
      path: '/viagens'
      fullPath: '/viagens'
      preLoaderRoute: typeof ViagensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresa/$id': {
      id: '/empresa/$id'
      path: '/empresa/$id'
      fullPath: '/empresa/$id'
      preLoaderRoute: typeof EmpresaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/': {
      id: '/painel/'
      path: '/painel'
      fullPath: '/painel/'
      preLoaderRoute: typeof PainelIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/agendamento': {
      id: '/painel/agendamento'
      path: '/painel/agendamento'
      fullPath: '/painel/agendamento'
      preLoaderRoute: typeof PainelAgendamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/avaliacoes': {
      id: '/painel/avaliacoes'
      path: '/painel/avaliacoes'
      fullPath: '/painel/avaliacoes'
      preLoaderRoute: typeof PainelAvaliacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/contatos': {
      id: '/painel/contatos'
      path: '/painel/contatos'
      fullPath: '/painel/contatos'
      preLoaderRoute: typeof PainelContatosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/empresa': {
      id: '/painel/empresa'
      path: '/painel/empresa'
      fullPath: '/painel/empresa'
      preLoaderRoute: typeof PainelEmpresaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/financeiro': {
      id: '/painel/financeiro'
      path: '/painel/financeiro'
      fullPath: '/painel/financeiro'
      preLoaderRoute: typeof PainelFinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/qrcode': {
      id: '/painel/qrcode'
      path: '/painel/qrcode'
      fullPath: '/painel/qrcode'
      preLoaderRoute: typeof PainelQrcodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/reservas': {
      id: '/painel/reservas'
      path: '/painel/reservas'
      fullPath: '/painel/reservas'
      preLoaderRoute: typeof PainelReservasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendarRoute: AgendarRoute,
  AjudaRoute: AjudaRoute,
  CadastroRoute: CadastroRoute,
  EmpresasRoute: EmpresasRoute,
  HistoricoRoute: HistoricoRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  PagamentosRoute: PagamentosRoute,
  PerfilRoute: PerfilRoute,
  QrcodeRoute: QrcodeRoute,
  ReservasRoute: ReservasRoute,
  ViagensRoute: ViagensRoute,
  EmpresaIdRoute: EmpresaIdRoute,
  PainelAgendamentoRoute: PainelAgendamentoRoute,
  PainelAvaliacoesRoute: PainelAvaliacoesRoute,
  PainelContatosRoute: PainelContatosRoute,
  PainelEmpresaRoute: PainelEmpresaRoute,
  PainelFinanceiroRoute: PainelFinanceiroRoute,
  PainelQrcodeRoute: PainelQrcodeRoute,
  PainelReservasRoute: PainelReservasRoute,
  PainelIndexRoute: PainelIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
